Allow creating new Builders using BaseMessageBuilder
ibm-messaging/kafka-connect-mq-sink pull request #21
Opened 2019-04-12 14:16 UTC by bltavares

The current `BaseMessageBuilder` interface defines some abstract methods,
without declaring their visibility.

This means it is by default, they are `package-private`, and we can't
create sub-classes extending the behavior.

One scenario where extending from another package is ideal would be when
extra headers are required to be sent to MQ. This commit changes the
modifier to be public so others could extend them.

Similar to https://github.com/ibm-messaging/kafka-connect-mq-source/pull/26

2019-04-12 14:39 UTC, AndrewJSchofield commented
This looks like a useful change. I'll take a look when I get some free time.

2019-04-14 19:40 UTC, AndrewJSchofield requested changes
Thanks for the PR and I think what you propose is sensible. It seems to me that all that is needed is to make getJMSMessage public. If you'd like to change the PR to include just that change and also accept the Contributor License Agreement, then I can approve it. Otherwise, I'm happy to close the PR and make that change myself.

2019-04-16 13:12 UTC, bltavares commented
I've updated the PR to only change the method signature.

I accept the CLA

2019-04-17 07:36 UTC, AndrewJSchofield approved these changes

2019-04-17 07:46 UTC, merged